const config = {
  dots: true,
  // variableWidth: true,
  slidesToScroll: 1,
  initialSlide: 0,
  arrows: false,
  speed: 500,
  slidesToShow: 1,
  adaptiveHeight: true,
  draggable: true,
  infinite: true,
  // infinite: true,
  // useTransform: false,
  // easing: 'linear',
  // responsive: [
  //   {
  //     breakpoint: 768,
  //     settings: {
  //       slidesToShow: 1,
  //       slidesToScroll: 1,
  //       initialSlide: 0,
  //       dots: false,
  //       variableWidth: true,
  //       arrows: false,
  //       infinite: true,
  //       speed: 500,
  //       autoplay: true,
  //       adaptiveHeight: true,
  //       draggable: true,
  //       easing: 'linear',
  //     },
  //   },
  //   {
  //     breakpoint: 576,
  //     settings: {
  //       slidesToShow: 1,
  //       slidesToScroll: 1,
  //       initialSlide: 0,
  //       dots: false,
  //       variableWidth: true,
  //       arrows: false,
  //       infinite: true,
  //       speed: 500,
  //       autoplay: true,
  //       adaptiveHeight: true,
  //       draggable: true,
  //       easing: 'linear',
  //     },
  //   },
  // ],
}

export default config
